# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1197, 844)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Main_tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.Main_tabWidget.setObjectName("Main_tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1181, 751))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.COM_groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.COM_groupBox.sizePolicy().hasHeightForWidth())
        self.COM_groupBox.setSizePolicy(sizePolicy)
        self.COM_groupBox.setMinimumSize(QtCore.QSize(400, 400))
        self.COM_groupBox.setMaximumSize(QtCore.QSize(400, 400))
        self.COM_groupBox.setObjectName("COM_groupBox")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.COM_groupBox)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 88, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.Com_label = QtWidgets.QLabel(self.COM_groupBox)
        # self.Com_label.setMinimumSize(QtCore.QSize(70, 0)) # [!!] 수정됨
        self.Com_label.setTextFormat(QtCore.Qt.AutoText)
        self.Com_label.setScaledContents(False)
        self.Com_label.setObjectName("Com_label")
        self.horizontalLayout_3.addWidget(self.Com_label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.Com_comboBox = QtWidgets.QComboBox(self.COM_groupBox)
        self.Com_comboBox.setMinimumSize(QtCore.QSize(90, 20))
        self.Com_comboBox.setMaximumSize(QtCore.QSize(90, 20))
        self.Com_comboBox.setObjectName("Com_comboBox")
        self.horizontalLayout_3.addWidget(self.Com_comboBox)
        self.Comrefresh_pushButton = QtWidgets.QPushButton(self.COM_groupBox)
        self.Comrefresh_pushButton.setObjectName("Comrefresh_pushButton")
        self.horizontalLayout_3.addWidget(self.Comrefresh_pushButton)
        spacerItem5 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem7 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.Baud_label = QtWidgets.QLabel(self.COM_groupBox)
        # self.Baud_label.setMinimumSize(QtCore.QSize(70, 0)) # [!!] 수정됨
        self.Baud_label.setObjectName("Baud_label")
        self.horizontalLayout_4.addWidget(self.Baud_label)
        self.Baud_comboBox = QtWidgets.QComboBox(self.COM_groupBox)
        self.Baud_comboBox.setMinimumSize(QtCore.QSize(90, 20))
        self.Baud_comboBox.setMaximumSize(QtCore.QSize(90, 20))
        self.Baud_comboBox.setObjectName("Baud_comboBox")
        self.horizontalLayout_4.addWidget(self.Baud_comboBox)
        spacerItem8 = QtWidgets.QSpacerItem(155, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem9 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem10 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem10)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.Comconnect_pushButton = QtWidgets.QPushButton(self.COM_groupBox)
        self.Comconnect_pushButton.setMinimumSize(QtCore.QSize(90, 30))
        self.Comconnect_pushButton.setMaximumSize(QtCore.QSize(90, 30))
        self.Comconnect_pushButton.setObjectName("Comconnect_pushButton")
        self.horizontalLayout_30.addWidget(self.Comconnect_pushButton)
        spacerItem11 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem11)
        self.Comdisconnect_pushButton = QtWidgets.QPushButton(self.COM_groupBox)
        self.Comdisconnect_pushButton.setMinimumSize(QtCore.QSize(90, 30))
        self.Comdisconnect_pushButton.setMaximumSize(QtCore.QSize(90, 30))
        self.Comdisconnect_pushButton.setObjectName("Comdisconnect_pushButton")
        self.horizontalLayout_30.addWidget(self.Comdisconnect_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_30)
        spacerItem12 = QtWidgets.QSpacerItem(20, 88, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem12)
        self.gridLayout_14.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.COM_groupBox, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.COM_groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.COM_groupBox_2.sizePolicy().hasHeightForWidth())
        self.COM_groupBox_2.setSizePolicy(sizePolicy)
        self.COM_groupBox_2.setMinimumSize(QtCore.QSize(400, 400))
        self.COM_groupBox_2.setMaximumSize(QtCore.QSize(400, 400))
        self.COM_groupBox_2.setObjectName("COM_groupBox_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.COM_groupBox_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        spacerItem13 = QtWidgets.QSpacerItem(20, 88, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem13)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        spacerItem14 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem14)
        self.Com_label_2 = QtWidgets.QLabel(self.COM_groupBox_2)
        # self.Com_label_2.setMinimumSize(QtCore.QSize(70, 0)) # [!!] 수정됨
        self.Com_label_2.setTextFormat(QtCore.Qt.AutoText)
        self.Com_label_2.setScaledContents(False)
        self.Com_label_2.setObjectName("Com_label_2")
        self.horizontalLayout_28.addWidget(self.Com_label_2)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem15)
        self.Com_comboBox_2 = QtWidgets.QComboBox(self.COM_groupBox_2)
        self.Com_comboBox_2.setMinimumSize(QtCore.QSize(90, 20))
        self.Com_comboBox_2.setMaximumSize(QtCore.QSize(90, 20))
        self.Com_comboBox_2.setObjectName("Com_comboBox_2")
        self.horizontalLayout_28.addWidget(self.Com_comboBox_2)
        self.Comrefresh_pushButton_2 = QtWidgets.QPushButton(self.COM_groupBox_2)
        self.Comrefresh_pushButton_2.setObjectName("Comrefresh_pushButton_2")
        self.horizontalLayout_28.addWidget(self.Comrefresh_pushButton_2)
        spacerItem16 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem16)
        self.verticalLayout_25.addLayout(self.horizontalLayout_28)
        spacerItem17 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_25.addItem(spacerItem17)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        spacerItem18 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem18)
        self.Baud_label_2 = QtWidgets.QLabel(self.COM_groupBox_2)
        # self.Baud_label_2.setMinimumSize(QtCore.QSize(70, 0)) # [!!] 수정됨
        self.Baud_label_2.setObjectName("Baud_label_2")
        self.horizontalLayout_29.addWidget(self.Baud_label_2)
        self.Baud_comboBox_2 = QtWidgets.QComboBox(self.COM_groupBox_2)
        self.Baud_comboBox_2.setMinimumSize(QtCore.QSize(90, 20))
        self.Baud_comboBox_2.setMaximumSize(QtCore.QSize(90, 20))
        self.Baud_comboBox_2.setObjectName("Baud_comboBox_2")
        self.horizontalLayout_29.addWidget(self.Baud_comboBox_2)
        spacerItem19 = QtWidgets.QSpacerItem(155, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem19)
        self.verticalLayout_25.addLayout(self.horizontalLayout_29)
        spacerItem20 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_25.addItem(spacerItem20)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.verticalLayout_25.addLayout(self.horizontalLayout_31)
        spacerItem21 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_25.addItem(spacerItem21)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.Comconnect_pushButton_2 = QtWidgets.QPushButton(self.COM_groupBox_2)
        self.Comconnect_pushButton_2.setMinimumSize(QtCore.QSize(90, 30))
        self.Comconnect_pushButton_2.setMaximumSize(QtCore.QSize(90, 30))
        self.Comconnect_pushButton_2.setObjectName("Comconnect_pushButton_2")
        self.horizontalLayout_32.addWidget(self.Comconnect_pushButton_2)
        spacerItem22 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem22)
        self.Comdisconnect_pushButton_2 = QtWidgets.QPushButton(self.COM_groupBox_2)
        self.Comdisconnect_pushButton_2.setMinimumSize(QtCore.QSize(90, 30))
        self.Comdisconnect_pushButton_2.setMaximumSize(QtCore.QSize(90, 30))
        self.Comdisconnect_pushButton_2.setObjectName("Comdisconnect_pushButton_2")
        self.horizontalLayout_32.addWidget(self.Comdisconnect_pushButton_2)
        self.verticalLayout_25.addLayout(self.horizontalLayout_32)
        spacerItem23 = QtWidgets.QSpacerItem(20, 88, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem23)
        self.gridLayout_15.addLayout(self.verticalLayout_25, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.COM_groupBox_2)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem24)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem25)
        self.Main_tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1161, 741))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_39.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem26)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Load0_groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.Load0_groupBox.setMinimumSize(QtCore.QSize(360, 150))
        self.Load0_groupBox.setMaximumSize(QtCore.QSize(360, 150))
        self.Load0_groupBox.setObjectName("Load0_groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Load0_groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem27 = QtWidgets.QSpacerItem(17, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem27)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Load0Currentnow_labeltxt = QtWidgets.QLabel(self.Load0_groupBox)
        # self.Load0Currentnow_labeltxt.setMinimumSize(QtCore.QSize(150, 20)) # [!!] 수정됨
        # self.Load0Currentnow_labeltxt.setMaximumSize(QtCore.QSize(150, 20)) # [!!] 수정됨
        self.Load0Currentnow_labeltxt.setObjectName("Load0Currentnow_labeltxt")
        self.horizontalLayout_6.addWidget(self.Load0Currentnow_labeltxt)
        self.Load0Currentnow_label = QtWidgets.QLabel(self.Load0_groupBox)
        self.Load0Currentnow_label.setMinimumSize(QtCore.QSize(170, 20))
        self.Load0Currentnow_label.setMaximumSize(QtCore.QSize(170, 20))
        self.Load0Currentnow_label.setStyleSheet("background-color: rgb(255,255,255);")
        self.Load0Currentnow_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Load0Currentnow_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Load0Currentnow_label.setMidLineWidth(0)
        self.Load0Currentnow_label.setText("")
        self.Load0Currentnow_label.setTextFormat(QtCore.Qt.AutoText)
        self.Load0Currentnow_label.setScaledContents(False)
        self.Load0Currentnow_label.setWordWrap(False)
        self.Load0Currentnow_label.setOpenExternalLinks(False)
        self.Load0Currentnow_label.setObjectName("Load0Currentnow_label")
        self.horizontalLayout_6.addWidget(self.Load0Currentnow_label)
        spacerItem28 = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem28)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem29 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem29)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem30)
        self.Load0_pushButton = QtWidgets.QPushButton(self.Load0_groupBox)
        self.Load0_pushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.Load0_pushButton.setMaximumSize(QtCore.QSize(100, 30))
        self.Load0_pushButton.setObjectName("Load0_pushButton")
        self.horizontalLayout_8.addWidget(self.Load0_pushButton)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem31)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        spacerItem32 = QtWidgets.QSpacerItem(17, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem32)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.Load0_groupBox)
        spacerItem33 = QtWidgets.QSpacerItem(17, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem33)
        self.En0_groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.En0_groupBox.setMinimumSize(QtCore.QSize(360, 150))
        self.En0_groupBox.setMaximumSize(QtCore.QSize(360, 150))
        self.En0_groupBox.setObjectName("En0_groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.En0_groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem34 = QtWidgets.QSpacerItem(17, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem34)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.En0Positionnow_labeltxt = QtWidgets.QLabel(self.En0_groupBox)
        # self.En0Positionnow_labeltxt.setMinimumSize(QtCore.QSize(150, 20)) # [!!] 수정됨
        # self.En0Positionnow_labeltxt.setMaximumSize(QtCore.QSize(150, 20)) # [!!] 수정됨
        self.En0Positionnow_labeltxt.setObjectName("En0Positionnow_labeltxt")
        self.horizontalLayout_10.addWidget(self.En0Positionnow_labeltxt, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.En0Positionnow_label = QtWidgets.QLabel(self.En0_groupBox)
        self.En0Positionnow_label.setMinimumSize(QtCore.QSize(170, 20))
        self.En0Positionnow_label.setMaximumSize(QtCore.QSize(170, 20))
        self.En0Positionnow_label.setStyleSheet("background-color: rgb(255,255,255);")
        self.En0Positionnow_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.En0Positionnow_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.En0Positionnow_label.setMidLineWidth(0)
        self.En0Positionnow_label.setText("")
        self.En0Positionnow_label.setTextFormat(QtCore.Qt.AutoText)
        self.En0Positionnow_label.setScaledContents(False)
        self.En0Positionnow_label.setWordWrap(False)
        self.En0Positionnow_label.setOpenExternalLinks(False)
        self.En0Positionnow_label.setObjectName("En0Positionnow_label")
        self.horizontalLayout_10.addWidget(self.En0Positionnow_label)
        spacerItem35 = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem35)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        spacerItem36 = QtWidgets.QSpacerItem(335, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem36)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem37)
        self.En0_pushButton = QtWidgets.QPushButton(self.En0_groupBox)
        self.En0_pushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.En0_pushButton.setMaximumSize(QtCore.QSize(100, 30))
        self.En0_pushButton.setObjectName("En0_pushButton")
        self.horizontalLayout_11.addWidget(self.En0_pushButton)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem38)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        spacerItem39 = QtWidgets.QSpacerItem(17, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem39)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.hz_groupBox = QtWidgets.QGroupBox("Monitoring Frequency")
        self.hz_groupBox.setMinimumSize(QtCore.QSize(360, 100))
        self.hz_groupBox.setMaximumSize(QtCore.QSize(360, 100))
        hz_layout = QtWidgets.QHBoxLayout()
        hz_label = QtWidgets.QLabel("Set Frequency:")
        self.hz_spinBox = QtWidgets.QSpinBox() 
        self.hz_spinBox.setSuffix(" Hz")
        self.hz_spinBox.setMinimum(1)
        self.hz_spinBox.setMaximum(100)
        self.hz_spinBox.setValue(10)
        self.hz_set_pushButton = QtWidgets.QPushButton("Set")
        hz_layout.addWidget(hz_label)
        hz_layout.addWidget(self.hz_spinBox)
        hz_layout.addStretch()
        hz_layout.addWidget(self.hz_set_pushButton)
        self.hz_groupBox.setLayout(hz_layout)
        # HZ 그룹박스를 verticalLayout_4에 추가
        self.verticalLayout_4.addWidget(self.hz_groupBox)
        self.verticalLayout_4.addWidget(self.En0_groupBox)
        spacerItem40 = QtWidgets.QSpacerItem(17, 34, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem40)
        self.Safty_groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.Safty_groupBox.setMinimumSize(QtCore.QSize(450, 300))
        self.Safty_groupBox.setMaximumSize(QtCore.QSize(420, 400))
        self.Safty_groupBox.setObjectName("Safty_groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Safty_groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem41 = QtWidgets.QSpacerItem(74, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem41, 0, 2, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Com_label_8 = QtWidgets.QLabel(self.Safty_groupBox)
        # self.Com_label_8.setMinimumSize(QtCore.QSize(50, 0)) # [!!] 수정됨
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Com_label_8.setFont(font)
        self.Com_label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Com_label_8.setObjectName("Com_label_8")
        self.verticalLayout_7.addWidget(self.Com_label_8)
        spacerItem42 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem42)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.DisplaceLimitMax_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.Safty_groupBox)
        self.DisplaceLimitMax_doubleSpinBox.setMinimumSize(QtCore.QSize(80, 20))
        self.DisplaceLimitMax_doubleSpinBox.setMaximumSize(QtCore.QSize(80, 20))
        self.DisplaceLimitMax_doubleSpinBox.setMaximum(999.99)
        self.DisplaceLimitMax_doubleSpinBox.setSingleStep(0.1)
        self.DisplaceLimitMax_doubleSpinBox.setObjectName("DisplaceLimitMax_doubleSpinBox")
        self.horizontalLayout_12.addWidget(self.DisplaceLimitMax_doubleSpinBox)
        spacerItem43 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem43)
        self.Com_label_6 = QtWidgets.QLabel(self.Safty_groupBox)
        # self.Com_label_6.setMinimumSize(QtCore.QSize(50, 0)) # [!!] 수정됨
        self.Com_label_6.setObjectName("Com_label_6")
        self.horizontalLayout_12.addWidget(self.Com_label_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.DisplaceLimitMin_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.Safty_groupBox)
        self.DisplaceLimitMin_doubleSpinBox.setMinimumSize(QtCore.QSize(80, 20))
        self.DisplaceLimitMin_doubleSpinBox.setMaximumSize(QtCore.QSize(80, 20))
        self.DisplaceLimitMin_doubleSpinBox.setMaximum(999.99)
        self.DisplaceLimitMin_doubleSpinBox.setSingleStep(0.1)
        self.DisplaceLimitMin_doubleSpinBox.setObjectName("DisplaceLimitMin_doubleSpinBox")
        self.horizontalLayout_13.addWidget(self.DisplaceLimitMin_doubleSpinBox)
        spacerItem44 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem44)
        self.Com_label_12 = QtWidgets.QLabel(self.Safty_groupBox)
        # self.Com_label_12.setMinimumSize(QtCore.QSize(50, 0)) # [!!] 수정됨
        self.Com_label_12.setObjectName("Com_label_12")
        self.horizontalLayout_13.addWidget(self.Com_label_12)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        spacerItem45 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem45)
        self.line = QtWidgets.QFrame(self.Safty_groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.Com_label_10 = QtWidgets.QLabel(self.Safty_groupBox)
        # self.Com_label_10.setMinimumSize(QtCore.QSize(50, 0)) # [!!] 수정됨
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Com_label_10.setFont(font)
        self.Com_label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Com_label_10.setObjectName("Com_label_10")
        self.verticalLayout_7.addWidget(self.Com_label_10)
        spacerItem46 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem46)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.ForceLimitMax_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.Safty_groupBox)
        self.ForceLimitMax_doubleSpinBox.setMinimumSize(QtCore.QSize(80, 20))
        self.ForceLimitMax_doubleSpinBox.setMaximumSize(QtCore.QSize(80, 20))
        self.ForceLimitMax_doubleSpinBox.setMaximum(999.99)
        self.ForceLimitMax_doubleSpinBox.setSingleStep(0.1)
        self.ForceLimitMax_doubleSpinBox.setObjectName("ForceLimitMax_doubleSpinBox")
        self.horizontalLayout_14.addWidget(self.ForceLimitMax_doubleSpinBox)
        spacerItem47 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem47)
        self.Com_label_13 = QtWidgets.QLabel(self.Safty_groupBox)
        # self.Com_label_13.setMinimumSize(QtCore.QSize(50, 0)) # [!!] 수정됨
        self.Com_label_13.setObjectName("Com_label_13")
        self.horizontalLayout_14.addWidget(self.Com_label_13)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem48 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem48)
        self.Com_label_14 = QtWidgets.QLabel(self.Safty_groupBox)
        # self.Com_label_14.setMinimumSize(QtCore.QSize(50, 0)) # [!!] 수정됨
        self.Com_label_14.setObjectName("Com_label_14")
        self.horizontalLayout_15.addWidget(self.Com_label_14)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        spacerItem49 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem49)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        spacerItem50 = QtWidgets.QSpacerItem(74, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem50, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.Safty_groupBox)
        self.horizontalLayout_39.addLayout(self.verticalLayout_4)
        spacerItem51 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem51)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.Motspeed_groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.Motspeed_groupBox.setObjectName("Motspeed_groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Motspeed_groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem52 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem52)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem53 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem53)
        self.MotorSpeed_checkBox = QtWidgets.QCheckBox(self.Motspeed_groupBox)
        self.MotorSpeed_checkBox.setObjectName("MotorSpeed_checkBox")
        self.horizontalLayout_7.addWidget(self.MotorSpeed_checkBox)
        spacerItem54 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem54)
        self.MotorSpeed_spinBox = QtWidgets.QSpinBox(self.Motspeed_groupBox)
        self.MotorSpeed_spinBox.setMinimumSize(QtCore.QSize(200, 20))
        self.MotorSpeed_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.MotorSpeed_spinBox.setObjectName("MotorSpeed_spinBox")
        self.MotorSpeed_spinBox.setMaximum(5000)
        self.horizontalLayout_7.addWidget(self.MotorSpeed_spinBox)
        self.MotorSpeedUnit_label = QtWidgets.QLabel(self.Motspeed_groupBox)
        # self.MotorSpeedUnit_label.setMinimumSize(QtCore.QSize(50, 0)) # [!!] 수정됨
        self.MotorSpeedUnit_label.setObjectName("MotorSpeedUnit_label")
        self.horizontalLayout_7.addWidget(self.MotorSpeedUnit_label)
        spacerItem55 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem55)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        spacerItem56 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem56)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem57 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem57)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Motor10_radioButton = QtWidgets.QRadioButton(self.Motspeed_groupBox)
        self.Motor10_radioButton.setMinimumSize(QtCore.QSize(100, 20))
        self.Motor10_radioButton.setMaximumSize(QtCore.QSize(100, 20))
        self.Motor10_radioButton.setObjectName("Motor10_radioButton")
        self.verticalLayout_8.addWidget(self.Motor10_radioButton)
        spacerItem58 = QtWidgets.QSpacerItem(18, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem58)
        self.Motor20_radioButton = QtWidgets.QRadioButton(self.Motspeed_groupBox)
        self.Motor20_radioButton.setMinimumSize(QtCore.QSize(100, 20))
        self.Motor20_radioButton.setMaximumSize(QtCore.QSize(100, 20))
        self.Motor20_radioButton.setObjectName("Motor20_radioButton")
        self.verticalLayout_8.addWidget(self.Motor20_radioButton)
        spacerItem59 = QtWidgets.QSpacerItem(18, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem59)
        self.Motor30_radioButton = QtWidgets.QRadioButton(self.Motspeed_groupBox)
        self.Motor30_radioButton.setMinimumSize(QtCore.QSize(100, 20))
        self.Motor30_radioButton.setMaximumSize(QtCore.QSize(100, 20))
        self.Motor30_radioButton.setObjectName("Motor30_radioButton")
        self.verticalLayout_8.addWidget(self.Motor30_radioButton)
        spacerItem60 = QtWidgets.QSpacerItem(18, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem60)
        self.Motor40_radioButton = QtWidgets.QRadioButton(self.Motspeed_groupBox)
        self.Motor40_radioButton.setMinimumSize(QtCore.QSize(100, 20))
        self.Motor40_radioButton.setMaximumSize(QtCore.QSize(100, 20))
        self.Motor40_radioButton.setObjectName("Motor40_radioButton")
        self.verticalLayout_8.addWidget(self.Motor40_radioButton)
        self.horizontalLayout_9.addLayout(self.verticalLayout_8)
        spacerItem61 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem61)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Motor50_radioButton = QtWidgets.QRadioButton(self.Motspeed_groupBox)
        self.Motor50_radioButton.setMinimumSize(QtCore.QSize(100, 20))
        self.Motor50_radioButton.setMaximumSize(QtCore.QSize(100, 20))
        self.Motor50_radioButton.setObjectName("Motor50_radioButton")
        self.verticalLayout_9.addWidget(self.Motor50_radioButton)
        spacerItem62 = QtWidgets.QSpacerItem(18, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem62)
        self.Motor100_radioButton = QtWidgets.QRadioButton(self.Motspeed_groupBox)
        self.Motor100_radioButton.setMinimumSize(QtCore.QSize(120, 20))
        self.Motor100_radioButton.setMaximumSize(QtCore.QSize(100, 20))
        self.Motor100_radioButton.setObjectName("Motor100_radioButton")
        self.verticalLayout_9.addWidget(self.Motor100_radioButton)
        spacerItem63 = QtWidgets.QSpacerItem(18, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem63)
        self.Motor200_radioButton = QtWidgets.QRadioButton(self.Motspeed_groupBox)
        self.Motor200_radioButton.setMinimumSize(QtCore.QSize(120, 20))
        self.Motor200_radioButton.setMaximumSize(QtCore.QSize(100, 20))
        self.Motor200_radioButton.setObjectName("Motor200_radioButton")
        self.verticalLayout_9.addWidget(self.Motor200_radioButton)
        spacerItem64 = QtWidgets.QSpacerItem(18, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem64)
        self.Motor300_radioButton = QtWidgets.QRadioButton(self.Motspeed_groupBox)
        self.Motor300_radioButton.setMinimumSize(QtCore.QSize(120, 20))
        self.Motor300_radioButton.setMaximumSize(QtCore.QSize(100, 20))
        self.Motor300_radioButton.setObjectName("Motor300_radioButton")
        self.verticalLayout_9.addWidget(self.Motor300_radioButton)
        self.horizontalLayout_9.addLayout(self.verticalLayout_9)
        spacerItem65 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem65)
        self.Setmotorspeed_pushButton = QtWidgets.QPushButton(self.Motspeed_groupBox)
        self.Setmotorspeed_pushButton.setMinimumSize(QtCore.QSize(90, 30))
        self.Setmotorspeed_pushButton.setMaximumSize(QtCore.QSize(90, 30))
        self.Setmotorspeed_pushButton.setObjectName("Setmotorspeed_pushButton")
        self.horizontalLayout_9.addWidget(self.Setmotorspeed_pushButton)
        spacerItem66 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem66)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        spacerItem67 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem67)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.Motspeed_groupBox)
        self.groupBox_9 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        spacerItem68 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem68)
        self.Jog_checkBox = QtWidgets.QCheckBox(self.groupBox_9)
        self.Jog_checkBox.setEnabled(True)
        self.Jog_checkBox.setObjectName("Jog_checkBox")
        self.horizontalLayout_33.addWidget(self.Jog_checkBox)
        spacerItem69 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem69)
        self.Jog_spinBox = QtWidgets.QSpinBox(self.groupBox_9)
        self.Jog_spinBox.setMinimumSize(QtCore.QSize(200, 20))
        self.Jog_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Jog_spinBox.setObjectName("Jog_spinBox")
        self.Jog_spinBox.setMaximum(5000)
        self.horizontalLayout_33.addWidget(self.Jog_spinBox)
        self.Com_label_15 = QtWidgets.QLabel(self.groupBox_9)
        # self.Com_label_15.setMinimumSize(QtCore.QSize(50, 0)) # [!!] 수정됨
        self.Com_label_15.setObjectName("Com_label_15")
        self.horizontalLayout_33.addWidget(self.Com_label_15)
        spacerItem70 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem70)
        self.verticalLayout_26.addLayout(self.horizontalLayout_33)
        spacerItem71 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_26.addItem(spacerItem71)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        spacerItem72 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem72)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.jog10_radioButton = QtWidgets.QRadioButton(self.groupBox_9)
        self.jog10_radioButton.setMinimumSize(QtCore.QSize(100, 20))
        self.jog10_radioButton.setMaximumSize(QtCore.QSize(100, 20))
        self.jog10_radioButton.setObjectName("jog10_radioButton")
        self.verticalLayout_27.addWidget(self.jog10_radioButton)
        spacerItem73 = QtWidgets.QSpacerItem(18, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_27.addItem(spacerItem73)
        self.jog20_radioButton = QtWidgets.QRadioButton(self.groupBox_9)
        self.jog20_radioButton.setMinimumSize(QtCore.QSize(100, 20))
        self.jog20_radioButton.setMaximumSize(QtCore.QSize(100, 20))
        self.jog20_radioButton.setObjectName("jog20_radioButton")
        self.verticalLayout_27.addWidget(self.jog20_radioButton)
        spacerItem74 = QtWidgets.QSpacerItem(18, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_27.addItem(spacerItem74)
        self.jog30_radioButton = QtWidgets.QRadioButton(self.groupBox_9)
        self.jog30_radioButton.setMinimumSize(QtCore.QSize(100, 20))
        self.jog30_radioButton.setMaximumSize(QtCore.QSize(100, 20))
        self.jog30_radioButton.setObjectName("jog30_radioButton")
        self.verticalLayout_27.addWidget(self.jog30_radioButton)
        spacerItem75 = QtWidgets.QSpacerItem(18, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_27.addItem(spacerItem75)
        self.jog40_radioButton = QtWidgets.QRadioButton(self.groupBox_9)
        self.jog40_radioButton.setMinimumSize(QtCore.QSize(100, 20))
        self.jog40_radioButton.setMaximumSize(QtCore.QSize(100, 20))
        self.jog40_radioButton.setObjectName("jog40_radioButton")
        self.verticalLayout_27.addWidget(self.jog40_radioButton)
        self.horizontalLayout_35.addLayout(self.verticalLayout_27)
        spacerItem76 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem76)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.jog50_radioButton = QtWidgets.QRadioButton(self.groupBox_9)
        self.jog50_radioButton.setMinimumSize(QtCore.QSize(120, 20))
        self.jog50_radioButton.setMaximumSize(QtCore.QSize(100, 20))
        self.jog50_radioButton.setObjectName("jog50_radioButton")
        self.verticalLayout_28.addWidget(self.jog50_radioButton)
        spacerItem77 = QtWidgets.QSpacerItem(18, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_28.addItem(spacerItem77)
        self.jog100_radioButton = QtWidgets.QRadioButton(self.groupBox_9)
        self.jog100_radioButton.setMinimumSize(QtCore.QSize(120, 20))
        self.jog100_radioButton.setMaximumSize(QtCore.QSize(100, 20))
        self.jog100_radioButton.setObjectName("jog100_radioButton")
        self.verticalLayout_28.addWidget(self.jog100_radioButton)
        spacerItem78 = QtWidgets.QSpacerItem(18, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_28.addItem(spacerItem78)
        self.jog200_radioButton = QtWidgets.QRadioButton(self.groupBox_9)
        self.jog200_radioButton.setMinimumSize(QtCore.QSize(120, 20))
        self.jog200_radioButton.setMaximumSize(QtCore.QSize(100, 20))
        self.jog200_radioButton.setObjectName("jog200_radioButton")
        self.verticalLayout_28.addWidget(self.jog200_radioButton)
        spacerItem79 = QtWidgets.QSpacerItem(18, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_28.addItem(spacerItem79)
        self.jog500_radioButton = QtWidgets.QRadioButton(self.groupBox_9)
        self.jog500_radioButton.setMinimumSize(QtCore.QSize(120, 20))
        self.jog500_radioButton.setMaximumSize(QtCore.QSize(100, 20))
        self.jog500_radioButton.setObjectName("jog500_radioButton")
        self.verticalLayout_28.addWidget(self.jog500_radioButton)
        self.horizontalLayout_35.addLayout(self.verticalLayout_28)
        self.horizontalLayout_34.addLayout(self.horizontalLayout_35)
        spacerItem80 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem80)
        self.Setjogspeed_pushButton = QtWidgets.QPushButton(self.groupBox_9)
        self.Setjogspeed_pushButton.setMinimumSize(QtCore.QSize(90, 30))
        self.Setjogspeed_pushButton.setMaximumSize(QtCore.QSize(90, 30))
        self.Setjogspeed_pushButton.setObjectName("Setjogspeed_pushButton")
        self.horizontalLayout_34.addWidget(self.Setjogspeed_pushButton)
        spacerItem81 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem81)
        self.verticalLayout_26.addLayout(self.horizontalLayout_34)
        self.gridLayout_12.addLayout(self.verticalLayout_26, 0, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        spacerItem82 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_31.addItem(spacerItem82)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        spacerItem83 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem83)
        self.Jogfowerd_pushButton = QtWidgets.QPushButton(self.groupBox_10)
        self.Jogfowerd_pushButton.setMinimumSize(QtCore.QSize(90, 30))
        self.Jogfowerd_pushButton.setMaximumSize(QtCore.QSize(90, 30))
        self.Jogfowerd_pushButton.setObjectName("Jogfowerd_pushButton")
        self.horizontalLayout_38.addWidget(self.Jogfowerd_pushButton)
        spacerItem84 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem84)
        self.Jogbackwerd_pushButton = QtWidgets.QPushButton(self.groupBox_10)
        self.Jogbackwerd_pushButton.setMinimumSize(QtCore.QSize(90, 30))
        self.Jogbackwerd_pushButton.setMaximumSize(QtCore.QSize(90, 30))
        self.Jogbackwerd_pushButton.setObjectName("Jogbackwerd_pushButton")
        self.horizontalLayout_38.addWidget(self.Jogbackwerd_pushButton)
        spacerItem85 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem85)
        self.verticalLayout_31.addLayout(self.horizontalLayout_38)
        spacerItem86 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_31.addItem(spacerItem86)
        self.gridLayout_18.addLayout(self.verticalLayout_31, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_10, 1, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_9)
        
        self.tension_groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.tension_groupBox.setObjectName("tension_groupBox")
        self.tension_groupBox.setTitle("시편 텐셔닝 (Pre-Tension)")
        tension_layout_grid = QtWidgets.QGridLayout(self.tension_groupBox)
        tension_layout_grid.setObjectName("tension_layout_grid")

        # 1. 속도 설정
        tension_speed_label = QtWidgets.QLabel("조정 속도:", self.tension_groupBox)
        tension_layout_grid.addWidget(tension_speed_label, 0, 0, 1, 1)
        
        self.tension_speed_spinBox = QtWidgets.QDoubleSpinBox(self.tension_groupBox)
        self.tension_speed_spinBox.setSuffix(" um/sec")
        self.tension_speed_spinBox.setMinimum(10)
        self.tension_speed_spinBox.setMaximum(1000.0)
        self.tension_speed_spinBox.setValue(10.0) # 기본값 10 um/sec
        self.tension_speed_spinBox.setSingleStep(10.0)
        self.tension_speed_spinBox.setObjectName("tension_speed_spinBox")
        tension_layout_grid.addWidget(self.tension_speed_spinBox, 0, 1, 1, 1)

        tension_force_label = QtWidgets.QLabel("감지 하중:", self.tension_groupBox)
        tension_layout_grid.addWidget(tension_force_label, 1, 0, 1, 1)
        
        self.tension_force_spinBox = QtWidgets.QDoubleSpinBox(self.tension_groupBox)
        self.tension_force_spinBox.setSuffix(" N")
        self.tension_force_spinBox.setMinimum(-999)
        self.tension_force_spinBox.setMaximum(999)
        self.tension_force_spinBox.setValue(0.1) # 기본값 0.1 N
        self.tension_force_spinBox.setDecimals(3)
        self.tension_force_spinBox.setSingleStep(0.1)
        self.tension_force_spinBox.setObjectName("tension_force_spinBox")
        tension_layout_grid.addWidget(self.tension_force_spinBox, 1, 1, 1, 1)

        tension_button_layout = QtWidgets.QHBoxLayout()
        spacerItem_tension = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        tension_button_layout.addItem(spacerItem_tension)
        
        self.tension_start_pushButton = QtWidgets.QPushButton("조정 시작", self.tension_groupBox)
        self.tension_start_pushButton.setObjectName("tension_start_pushButton")
        tension_button_layout.addWidget(self.tension_start_pushButton)
        
        self.tension_stop_pushButton = QtWidgets.QPushButton("수동 정지", self.tension_groupBox)
        self.tension_stop_pushButton.setObjectName("tension_stop_pushButton")
        tension_button_layout.addWidget(self.tension_stop_pushButton)
        
        tension_layout_grid.addLayout(tension_button_layout, 2, 0, 1, 2)
        
        self.verticalLayout_12.addWidget(self.tension_groupBox)
        
        self.horizontalLayout_39.addLayout(self.verticalLayout_12)
        spacerItem87 = QtWidgets.QSpacerItem(40, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem87)
        self.Main_tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.tabWidget = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.textEdit = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 471, 71))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 70, 711, 491))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.graphicsView = PlotWidget(self.gridLayoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_6.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.testValuesWidget = QtWidgets.QWidget(self.tab_4)
        self.testValuesWidget.setGeometry(QtCore.QRect(780, 70, 351, 100)) 
        self.testValuesWidget.setObjectName("testValuesWidget")
        
        self.formLayout = QtWidgets.QFormLayout(self.testValuesWidget)
        self.formLayout.setObjectName("formLayout")

        self.static_load_label = QtWidgets.QLabel(self.testValuesWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.static_load_label.setFont(font)
        self.static_load_label.setText("현재 하중 (N):")
        self.static_load_label.setObjectName("static_load_label")
        
        self.test_load_label = QtWidgets.QLabel(self.testValuesWidget)
        self.test_load_label.setFont(font)
        self.test_load_label.setStyleSheet("background-color: rgb(255,255,255); border: 1px solid black; padding: 2px;")
        self.test_load_label.setText("0.000")
        self.test_load_label.setObjectName("test_load_label")

        self.formLayout.addRow(self.static_load_label, self.test_load_label)

        # 2. 모터 위치 라벨
        self.static_pos_label = QtWidgets.QLabel(self.testValuesWidget)
        self.static_pos_label.setFont(font)
        self.static_pos_label.setText("현재 변위 (um):")
        self.static_pos_label.setObjectName("static_pos_label")
        
        self.test_pos_label = QtWidgets.QLabel(self.testValuesWidget)
        self.test_pos_label.setFont(font)
        self.test_pos_label.setStyleSheet("background-color: rgb(255,255,255); border: 1px solid black; padding: 2px;")
        self.test_pos_label.setText("0.0")
        self.test_pos_label.setObjectName("test_pos_label")
        
        self.formLayout.addRow(self.static_pos_label, self.test_pos_label)

        self.layoutWidget = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget.setGeometry(QtCore.QRect(780, 560, 352, 170))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        spacerItem88 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem88)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem89 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem89)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.Basicteststart_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.Basicteststart_pushButton.setMinimumSize(QtCore.QSize(90, 30))
        self.Basicteststart_pushButton.setMaximumSize(QtCore.QSize(90, 30))
        self.Basicteststart_pushButton.setObjectName("Basicteststart_pushButton")
        self.horizontalLayout_22.addWidget(self.Basicteststart_pushButton)
        spacerItem90 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem90)
        self.Basicteststop_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.Basicteststop_pushButton.setMinimumSize(QtCore.QSize(90, 30))
        self.Basicteststop_pushButton.setMaximumSize(QtCore.QSize(90, 30))
        self.Basicteststop_pushButton.setObjectName("Basicteststop_pushButton")
        self.horizontalLayout_22.addWidget(self.Basicteststop_pushButton)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_22)
        spacerItem91 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem91)
        self.verticalLayout_20.addLayout(self.horizontalLayout_25)

        self.horizontalLayout_reset = QtWidgets.QHBoxLayout()
        self.horizontalLayout_reset.setObjectName("horizontalLayout_reset")
        spacerItem_reset_left = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_reset.addItem(spacerItem_reset_left)
        self.Basictestreset_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.Basictestreset_pushButton.setMinimumSize(QtCore.QSize(90, 30))
        self.Basictestreset_pushButton.setMaximumSize(QtCore.QSize(90, 30))
        self.Basictestreset_pushButton.setObjectName("Basictestreset_pushButton")
        self.horizontalLayout_reset.addWidget(self.Basictestreset_pushButton)
        spacerItem_reset_right = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_reset.addItem(spacerItem_reset_right)
        self.verticalLayout_20.addLayout(self.horizontalLayout_reset)

        spacerItem92 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem92)
        
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 0, 441, 71))
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_5)
        
        self.layoutWidget.setGeometry(QtCore.QRect(780, 560, 352, 170)) 

        self.layoutWidget1.setGeometry(QtCore.QRect(770, 500, 377, 194))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        spacerItem93 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem93)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        spacerItem94 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem94)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.Com_label_11 = QtWidgets.QLabel(self.layoutWidget1)
        # self.Com_label_11.setMinimumSize(QtCore.QSize(70, 20)) # [!!] 수정됨
        # self.Com_label_11.setMaximumSize(QtCore.QSize(70, 20)) # [!!] 수정됨
        self.Com_label_11.setObjectName("Com_label_11")
        self.horizontalLayout_24.addWidget(self.Com_label_11)
        self.torq_set_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.torq_set_doubleSpinBox.setMinimumSize(QtCore.QSize(200, 20))
        self.torq_set_doubleSpinBox.setMaximumSize(QtCore.QSize(200, 20))
        self.torq_set_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.torq_set_doubleSpinBox.setMaximum(999.99)
        self.torq_set_doubleSpinBox.setObjectName("torq_set_doubleSpinBox")
        self.horizontalLayout_24.addWidget(self.torq_set_doubleSpinBox)
        self.verticalLayout_19.addLayout(self.horizontalLayout_24)
        spacerItem95 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_19.addItem(spacerItem95)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.Torqueteststart_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.Torqueteststart_pushButton.setMinimumSize(QtCore.QSize(90, 30))
        self.Torqueteststart_pushButton.setMaximumSize(QtCore.QSize(90, 30))
        self.Torqueteststart_pushButton.setObjectName("Torqueteststart_pushButton")
        self.horizontalLayout_23.addWidget(self.Torqueteststart_pushButton)
        spacerItem96 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem96)
        self.Torqueteststop_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.Torqueteststop_pushButton.setMinimumSize(QtCore.QSize(90, 30))
        self.Torqueteststop_pushButton.setMaximumSize(QtCore.QSize(90, 30))
        self.Torqueteststop_pushButton.setObjectName("Torqueteststop_pushButton")
        self.horizontalLayout_23.addWidget(self.Torqueteststop_pushButton)
        self.verticalLayout_19.addLayout(self.horizontalLayout_23)
        spacerItem97 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem97)
        self.horizontalLayout_26.addLayout(self.verticalLayout_19)
        spacerItem98 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem98)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.verticalLayout_24.addWidget(self.tabWidget)
        self.gridLayout_13.addLayout(self.verticalLayout_24, 0, 0, 1, 1)
        self.Main_tabWidget.addTab(self.tab_3, "")

        self.tab_data = QtWidgets.QWidget()
        self.tab_data.setObjectName("tab_data")
        self.data_tab_layout = QtWidgets.QVBoxLayout(self.tab_data)
        placeholder_label = QtWidgets.QLabel("데이터 탭 콘텐츠가 여기에 표시됩니다.")
        placeholder_label.setAlignment(QtCore.Qt.AlignCenter)
        self.data_tab_layout.addWidget(placeholder_label)
        self.Main_tabWidget.addTab(self.tab_data, "") # <--- 추가
        
        self.gridLayout.addWidget(self.Main_tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1197, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Main_tabWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.COM_groupBox.setTitle(_translate("MainWindow", "Motor"))
        self.Com_label.setText(_translate("MainWindow", "COM port"))
        self.Comrefresh_pushButton.setText(_translate("MainWindow", "Refresh"))
        self.Baud_label.setText(_translate("MainWindow", "Baud-rate"))
        self.Comconnect_pushButton.setText(_translate("MainWindow", "Connect"))
        self.Comdisconnect_pushButton.setText(_translate("MainWindow", "Disconnect"))
        self.COM_groupBox_2.setTitle(_translate("MainWindow", "Load Cell"))
        self.Com_label_2.setText(_translate("MainWindow", "COM port"))
        self.Comrefresh_pushButton_2.setText(_translate("MainWindow", "Refresh"))
        self.Baud_label_2.setText(_translate("MainWindow", "Baud-rate"))
        self.Comconnect_pushButton_2.setText(_translate("MainWindow", "Connect"))
        self.Comdisconnect_pushButton_2.setText(_translate("MainWindow", "Disconnect"))
        self.Main_tabWidget.setTabText(self.Main_tabWidget.indexOf(self.tab_2), _translate("MainWindow", "COM set"))
        self.Load0_groupBox.setTitle(_translate("MainWindow", "Load to 0 Point Set"))
        self.Load0Currentnow_labeltxt.setText(_translate("MainWindow", "Load Cell Force"))
        self.Load0_pushButton.setText(_translate("MainWindow", "Set"))
        self.En0_groupBox.setTitle(_translate("MainWindow", "Encoder to 0 Point Set"))
        self.En0Positionnow_labeltxt.setText(_translate("MainWindow", "Encoder Position"))
        self.En0_pushButton.setText(_translate("MainWindow", "Set"))
        self.Safty_groupBox.setTitle(_translate("MainWindow", "Safety Limit"))
        self.Com_label_8.setText(_translate("MainWindow", "Displacement(mm)"))
        self.Com_label_6.setText(_translate("MainWindow", "High"))
        self.Com_label_12.setText(_translate("MainWindow", "Low"))
        self.Com_label_10.setText(_translate("MainWindow", "Force(N)"))
        self.Com_label_13.setText(_translate("MainWindow", "Displacement"))
        self.Com_label_14.setText(_translate("MainWindow", "Displacement")) # [!!] 이 라벨도 텍스트가 있네요.
        self.Motspeed_groupBox.setTitle(_translate("MainWindow", "Motor speed setting"))
        self.MotorSpeed_checkBox.setText(_translate("MainWindow", "사용자 지정"))
        self.MotorSpeedUnit_label.setText(_translate("MainWindow", "[um/sec]"))
        self.Motor10_radioButton.setText(_translate("MainWindow", "10[um/sec]"))
        self.Motor20_radioButton.setText(_translate("MainWindow", "20[um/sec]"))
        self.Motor30_radioButton.setText(_translate("MainWindow", "30[um/sec]"))
        self.Motor40_radioButton.setText(_translate("MainWindow", "40[um/sec]"))
        self.Motor50_radioButton.setText(_translate("MainWindow", "50[um/sec]"))
        self.Motor100_radioButton.setText(_translate("MainWindow", "100[um/sec]"))
        self.Motor200_radioButton.setText(_translate("MainWindow", "200[um/sec]"))
        self.Motor300_radioButton.setText(_translate("MainWindow", "300[um/sec]"))
        self.Setmotorspeed_pushButton.setText(_translate("MainWindow", "Set Speed"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Jog speed setting"))
        self.Jog_checkBox.setText(_translate("MainWindow", "사용자 지정"))
        self.Com_label_15.setText(_translate("MainWindow", "[um/sec]"))
        self.jog10_radioButton.setText(_translate("MainWindow", "10[um/sec]"))
        self.jog20_radioButton.setText(_translate("MainWindow", "20[um/sec]"))
        self.jog30_radioButton.setText(_translate("MainWindow", "30[um/sec]"))
        self.jog40_radioButton.setText(_translate("MainWindow", "40[um/sec]"))
        self.jog50_radioButton.setText(_translate("MainWindow", "50[um/sec]"))
        self.jog100_radioButton.setText(_translate("MainWindow", "100[um/sec]"))
        self.jog200_radioButton.setText(_translate("MainWindow", "200[um/sec]"))
        self.jog500_radioButton.setText(_translate("MainWindow", "500[um/sec]"))
        self.Setjogspeed_pushButton.setText(_translate("MainWindow", "Set Speed"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Jog"))
        self.Jogfowerd_pushButton.setText(_translate("MainWindow", "Compression"))
        self.Jogbackwerd_pushButton.setText(_translate("MainWindow", "Tensile"))

        self.tension_groupBox.setTitle(_translate("MainWindow", "Pre-Tension"))
        self.tension_speed_spinBox.setSuffix(_translate("MainWindow", " um/sec"))
        self.tension_force_spinBox.setSuffix(_translate("MainWindow", " N"))
        self.tension_start_pushButton.setText(_translate("MainWindow", "조정 시작"))
        self.tension_stop_pushButton.setText(_translate("MainWindow", "수동 정지"))
        
        self.Main_tabWidget.setTabText(self.Main_tabWidget.indexOf(self.tab), _translate("MainWindow", "Setting"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Basic Tensile Test</span><span style=\" font-size:10pt;\"><br />The specimen is stretched until fracture, and the torque value observed during the test is recorded and analyzed.</span></p></body></html>"))
        self.Basicteststart_pushButton.setText(_translate("MainWindow", "Start"))
        self.Basicteststop_pushButton.setText(_translate("MainWindow", "Stop"))
        self.Basictestreset_pushButton.setText(_translate("MainWindow", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "기본 인장 시험"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Torque-Controlled Tensile Test</span><span style=\" font-size:10pt;\"><br />A constant input torque is applied to the specimen, and its resulting deformation and behavior are observed.</span></p></body></html>"))
        self.Com_label_11.setText(_translate("MainWindow", "Torque[N]"))
        self.Torqueteststart_pushButton.setText(_translate("MainWindow", "Start"))
        self.Torqueteststop_pushButton.setText(_translate("MainWindow", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "토크 인장 시험"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "반복 인장 시험"))
        self.Main_tabWidget.setTabText(self.Main_tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Test"))
        

        self.Main_tabWidget.setTabText(self.Main_tabWidget.indexOf(self.tab_data), _translate("MainWindow", "Data"))
        
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())